### ISSUE TITLE
keys are not updated and graphic glitch with background.

### ISSUE THREAD

**Issue by Rifz42** [SpectralVectors/BLUI#1]
Hi This looks cool!  thanks for making it.   I've got it installed and restarted, but the hotkeys have not been changed from the default.  also there is some graphical glitching with the background images and grid..  how would fix the keys and turn off the background?  thank you!!

![image](https://user-images.githubusercontent.com/63940800/141643021-9645351e-c48a-44d1-bde8-089692cb4d89.png)

**Comment by SpectralVectors** [comment]
To fix the keys you can go to Edit > Preferences > Keymap, and then, in the dropdown that says 'Blender', choose 'BLUI Keymap'. If that option doesn't exist, then click 'Import' and navigate to BLUI_Keymap.py and install that.

For the graphical glitches I would first try just switching the viewport shading to Solid/Wireframe/Rendered, basically anything else, and then switch back and see if the glitches remain. If they do, try switching the HDRI in the Viewport Shading dropdown menu, and if all that fails, just turn the World Opacity down to zero, you won't see the HDRI in the background of your scene, but your object will still be lit by it.

**Comment by Rifz42** [comment]
Thank you!  I'll try that.
